<?xml version="1.0" encoding="utf-8"?><Database Name="RegistrationDB" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.OTP_Verification" Member="OTP_Verifications">
    <Type Name="OTP_Verification">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="GenerationDT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustomerID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </Type>
  </Table>
</Database>